# frozen_string_literal: true

require_relative 'config'

cfg = Config.load_from_yaml

Vagrant.configure('2') do |config|
  config.vm.box = 'cloud-image/arch-linux'
  config.vm.box_version = '20260501.523211.0'
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = cfg.virtualbox_memory
    vb.cpus = cfg.virtualbox_cpus
  end

  config.vm.provision 'shell' do |s|
    s.env = {
      'APP_DIR' => '/home/vagrant/kronika',
      'GITHUB_USER' => cfg.github_user,
      'GITHUB_TOKEN' => cfg.github_token,
      'GITHUB_REMOTE' => cfg.git_remote,
      'GIT_NAME' => cfg.git_name,
      'GIT_EMAIL' => cfg.git_email,
      'RUBY_VERSION' => cfg.ruby_version.join('.'),
      'RUBY_VERSION_MAJOR' => cfg.ruby_version[0],
      'RUBY_VERSION_MINOR' => cfg.ruby_version[1],
      'RUBY_VERSION_PATCH' => cfg.ruby_version[2]
    }

    s.path = 'provision.sh'
  end
end
